start on starting framework
stop on stopping framework

export LANG LC_ALL

pre-start script
    source /etc/upstart/functions
    
    # Path to our screensaver folder
    SS_DIR="/mnt/us/onlinescreensaver/screensaver"
    # Kindle's internal screensaver folder
    KINDLE_SS_DIR="/usr/share/blanket/screensaver"
    
    # Ensure our directory exists
    mkdir -p "$SS_DIR"
    
    # Bind mount our folder over Kindle's
    if ! grep -q " $KINDLE_SS_DIR " /proc/mounts; then
        f_log I onlinescreensaver-mount "mounting standalone screensavers"
        mount --bind "$SS_DIR" "$KINDLE_SS_DIR"
    fi
    
    return 0
end script

post-stop script
    source /etc/upstart/functions
    KINDLE_SS_DIR="/usr/share/blanket/screensaver"
    
    if grep -q "^fsp $KINDLE_SS_DIR" /proc/mounts; then
        f_log I onlinescreensaver-mount "unmounting standalone screensavers"
        umount -l "$KINDLE_SS_DIR"
    fi
    
    return 0
end script
